### PR TITLE
show custom dialog on bad input

### LINKED ISSUE #62: Easier to read error messages?
image

Potentially making an easier error message with your own message box, as most users will not understand nor need the unhandled exception part. No good reason to clamp it to a valid number, as then users may continually try putting a negative offset. Just a suggestion for a future update and not application breaking😄

### PR DESCRIPTION
**Pull request by a1xd**
fixes #62

inputmsg

### CODE REVIEW

File: grapher/MessageDialog.cs [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+namespace grapher
+{
+    public partial class MessageDialog : Form
+    {
+        public MessageDialog(string msg, string title = "")
+        {
+            InitializeComponent();
+            Icon = Icon.ExtractAssociatedIcon(Application.ExecutablePath);
+            Text = title;
+            messageLabel.Text = msg;
```
Comment (JacobPalecki) [inline grapher/MessageDialog.cs:20]: Can you please rename to "message"

File: grapher/MessageDialog.cs [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+using System.Linq;
+using System.Text;
+using System.Threading.Tasks;
+using System.Windows.Forms;
+
+namespace grapher
+{
+    public partial class MessageDialog : Form
+    {
+        public MessageDialog(string msg, string title = "")
```
Comment (a1xd) [inline grapher/MessageDialog.cs:15]:
```suggestion
        public MessageDialog(string message, string title = "")
```

File: grapher/MessageDialog.cs [hunk 3]
```diff
@@ -0,0 +1,24 @@
...
+namespace grapher
+{
+    public partial class MessageDialog : Form
+    {
+        public MessageDialog(string message, string title = "")
+        {
+            InitializeComponent();
+            Icon = Icon.ExtractAssociatedIcon(Application.ExecutablePath);
+            Text = title;
+            messageLabel.Text = msg;
```
Comment (a1xd) [inline grapher/MessageDialog.cs:20]:
```suggestion
            messageLabel.Text = message;
```

**Review by JacobPalecki — APPROVED** [review]
